version: '3'
services:
  app:
    image: project2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080  # Specify the port explicitly
      - MONGODB_URI=mongodb+srv://pemitchell:TThycxG6X78dXSH0@nytbooksdb.5ugif.mongodb.net/BooksDatabase?retryWrites=true&w=majority&appName=NYTBooksDB
      - nyt.api.key=GJULyrhinH6fKxvLBST05RLKgeyxAusr
    ports:
      - "8080:8080"  # Map the application port to the host
    depends_on: []  # No dependencies since we are using Atlas
    networks:
      - app-network

networks:
  app-network:
