version: '1.0'

services:
  app:
    image: project2:latest  # Image for your Spring Boot app
    build:
      context: .  # Assuming Dockerfile is in the root directory
    ports:
      - "8080:8080"  # Mapping container port to host
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin@cluster0.bgnil.mongodb.net/cst438-project2?retryWrites=true&w=majority&ssl=true&appName=cluster0
    depends_on:
      - mongodb  # Ensure MongoDB is started before the app
    networks:
      - app-network

  mongodb:
    image: mongo:latest  # Official MongoDB image
    container_name: mongodb
    ports:
      - "27017:27017"  # Exposing MongoDB's default port
    volumes:
      - mongo-data:/data/db  # Persisting MongoDB data
    networks:
      - app-network

volumes:
  mongo-data:  # Named volume to persist MongoDB data

networks:
  app-network:  # Network for app and MongoDB to communicate
